### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by kyumin2lee**
Some link fixes plus a credit to a user for the images and the image
action.

### CODE REVIEW

**Comment by kyumin2lee** [comment]
Also updated Map List to those currently in Rotation. Will work on other stuff later ;)

**Comment by kyumin2lee** [comment]
I also realized that we amassed a lot of maps, and now the list is looking a big.. long. To combat that I've made a fourth column exclusively for Payload maps, and moved the small 'Other' category to the KOTH column. I've also prepared the banner for the .svg file.

**Comment by kyumin2lee** [comment]
Placed the new logos in appropriate folders, and started working on
editing the maps.html thoroughly.

**Comment by peterpacz1** [comment]
Looks good, merging...

**Pull request merged**
